2020-06-22 17:42:28,580 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 17:47:33,458 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 17:48:36,296 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 17:49:41,156 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 17:49:59,073 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 17:50:44,928 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 17:51:02,619 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 17:51:16,056 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 17:51:38,630 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 17:52:08,299 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 17:52:43,778 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:10:07,356 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:10:28,816 ERROR: Exception on /auth/register [POST] [in c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ajshe\microblog2\app\auth\routes.py", line 49, in register
    msg = Message(author=admin, recipient=user,
NameError: name 'Message' is not defined
2020-06-22 19:11:15,637 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:16:40,085 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:21:25,935 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:22:11,061 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:24:52,637 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:26:29,061 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:28:45,676 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:31:04,568 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:34:10,862 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:35:46,202 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:37:49,868 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-22 19:39:14,620 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:74]
2020-06-23 01:29:14,403 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:26:00,978 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:28:40,765 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:29:24,956 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:29:57,023 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:30:13,295 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:31:45,651 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:32:33,469 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:33:48,924 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:34:25,618 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:34:33,315 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:34:59,766 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:36:11,488 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:48:19,092 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:48:27,207 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:49:01,110 ERROR: Exception on /api/users/3 [GET] [in c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ajshe\microblog2\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ajshe\microblog2\app\api\users.py", line 7, in get_user
    return jsonify(User.query.get_or_404(id).to_dict())
  File "C:\Users\ajshe\microblog2\app\models.py", line 153, in to_dict
    'self': url_for('api.get_user', id=self.id),
NameError: name 'url_for' is not defined
2020-06-23 03:50:05,977 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 03:58:07,037 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 04:06:13,065 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 04:16:43,317 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 04:40:10,458 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 04:40:37,913 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
2020-06-23 04:40:43,711 INFO: Microblog Startup [in C:\Users\ajshe\microblog2\app\__init__.py:77]
